# Generated by Django 3.2.7 on 2021-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_auto_20211003_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.CharField(choices=[('09:30', '09:30'), ('12:00', '12:00'), ('15:30', '15:30'), ('18:00', '18:00'), ('21:30', '21:30')], max_length=30),
        ),
    ]
